### ISSUE TITLE
Need login() to support AuthSubToken

### ISSUE THREAD

**Issue by matlink** [NoMore201/googleplay-api#2]
In order for gplaycli to be able to retrieve and use tokens from token-dispenser server, I need your login() method to support AuthSubToken as in https://github.com/matlink/gplaycli/blob/master/python3/ext_libs/googleplay_api/googleplay.py#L167#L168 as a replacement for the password.

**Comment by NoMore201** [comment]
I think I can implement it, remember that you need to save also the Google Service Framework ID (in short gsf-id) generated by the credentials login. If you use an external one it probably won't work.

Probably the correct requirements for the login() method are these:
* **First time login**
    1 user calls login() with email and password
    2 user saves GSF-ID and AuthSubToken in the application state
* **Subsequent login**
    1 user calls login() with GSF-ID and AuthSubToken

Also, i think there's no need to save AC2DMtoken, because it is needed only on first time login. I will fix that and let you know asap.

**Comment by matlink** [comment]
So it is not possible to get the GSFID with only the AuthSubToken?

**Comment by NoMore201** [comment]
No, you need email and password to retrieve it.

**Comment by matlink** [comment]
Well token dispenser is able to get a GSFID while returning the AuthSubToken.

**Comment by NoMore201** [comment]
Right, because it saves email and password in a text file, so every time it launches, he gets a new ac2dmtoken with the credentials, then a new gsf-id and then it stays idle producing new AuthSubTokens for every requests.

This is the initalization of the Java API used by token-dispenser:
https://github.com/yeriomin/play-store-api/blob/8e1450505da700dbb2a8264e256149c244900379/src/main/java/com/github/yeriomin/playstoreapi/PlayStoreApiBuilder.java#L62

**Comment by NoMore201** [comment]
Made changes in commit 2276f8d.
Also made some tests, and I verified that gsfId is needed as a default header.

The only way i can see to fix this is to save the gsfId in the googleplay-api state (for example in a `config.py` module like the one before https://github.com/egirault/googleplay-api/blob/master/config.py), and ask only for the authSubToken.

In my opinion this isn't a good idea, because: 

* If I have multiple istances of googleplay-api running, with the `config.py` method they will share the same gsfId, but each one of them will use a different authSubToken, generated by different accounts with different gsfId. So it will not work for everyone.
* Data related to login should be saved by the application using this library, not by the library itself.

**Comment by matlink** [comment]
Yes, I don't need your library to store GSFID, but instead wanted it to support AuthSubToken and GSFID parameters to the login() method.
Token dispenser is able to give the GSFID alongside the AuthSubToken. I'll then patch gplaycli to get GSFID + AuthSubToken instead of the token only.

**Comment by NoMore201** [comment]
Do you mean something like this?

```
api = GooglePlayAPI(debug=true)
api.retrieveNewGsfId()
api.login(email=None, password=None, authSubToken=<token>)
```

**Comment by matlink** [comment]
No, I got what I wanted already. I needed `api.login(authSubToken=token, gsfId=gsf_id)`
