### ISSUE TITLE
nb_result does not work

### ISSUE THREAD

**Issue by matlink** [NoMore201/googleplay-api#7]
The nb_result param for search is ignored https://github.com/NoMore201/googleplay-api/blob/master/gpapi/googleplay.py#L274

**Comment by NoMore201** [comment]
Before making changes, this needs to be discussed here. The new API for search works in a different way.

Each search returns a cluster, which is basically a container for DocV2 elements. Now there are two cases:

1. **Search query is too general**, for example we search for `fire`. In this case, cluster contains only 1 doc, and this doc contains 20 apps. Cluster contains also a containerMetadata object, with the url for the next page (to search for more than 20 apps). This basically is what you have in gplaycli search() function.

2. **Search query is specific** like `whatsapp` or `telegram`. In this case the cluster contains 4 docs, each one with a specific role:
    - **doc1** contains the exact result of the query, for example the whatsapp or telegram application
    - **doc2** corresponds to the `You Might Also Like` section, and contains other less related apps.
    - **doc3** corresponds to the `Similar Apps` section of the play store, with some apps.
    - **doc4** corresponds to the `More Result` section, with some apps.

Obviously, there is no url for the next page, because there is no sense in searching for other result if the query is specific. To better understand this result, this is the corresponding Play Store view:

![image](http://playstoredownloadi.com/wp-content/uploads/2016/12/play-store-app-download.jpg)

The current code just grabs every child of every doc and puts them in an iterable object:
https://github.com/NoMore201/googleplay-api/blob/0a5e2700494568f17dace1f1e4a11892f90da7fb/gpapi/googleplay.py#L288
so it makes no difference if we are in case (1) or (2). In my opinion we can do one of the following:

- Stick with this behaviour and add a check for the next page. If it doesn't exist (like in case 2), the number of results will always be at max 20. So even if `nb_results = 54`, result will contain only 20 elements.
- Return a different object in case(2) with each different section, but I don't think it fits well with applications using this library.

Let me know what you think

**Comment by matlink** [comment]
well I think we could stick with this behaviour. we could iterate over next page URLs until  nb_result is reached or no more page.

**Comment by matlink** [comment]
When running your test.py file, I've got:
```
nb_result: 34
number of results: 22
```

**Comment by NoMore201** [comment]
Yes because test.py searches for `telegram`, which is a specific query (case (2) of the previous answer) and returns ~20  apps. I passed to the function `nb_result = 34` to show the behaviour of the specific search.

If you do instead:
```
search('fire', 34, None)
```
you get
```
nb_result: 34
number of results: 34
```

because there are more pages to browse.
